os: linux
dist: bionic

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - lcov
  
before_script:
  - sudo apt remove --purge cmake -y
  #- sudo snap install cmake --classic --channel=latest/stable
  - CMAKE_DOWNLOAD=https://github.com/Kitware/CMake/releases/download/v3.19.1/cmake-3.19.1-Linux-x86_64.sh
  - CMAKE_INSTALLER=install-cmake.sh
  - curl -sSL ${CMAKE_DOWNLOAD} -o ${CMAKE_INSTALLER}
  - chmod +x ${CMAKE_INSTALLER}
  - sudo ./${CMAKE_INSTALLER} --prefix=/usr/local --skip-license
  - cmake --version
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DMAZE_BUILD_TESTS=ON -DMAZE_CODE_COVERAGE=ON

script:
  - make -j4
  - make Maze_tests_coverage
