dist: bionic
sudo: require

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - lcov
  snaps:
    - name: cmake
      confinement: classic
      channel: latest/stable
  
before_script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DMAZE_BUILD_TESTS=ON -DMAZE_CODE_COVERAGE=ON

script:
  - make -j4
  - make Maze_tests_coverage
